### ISSUE TITLE
Cannot copy format `png`

### ISSUE THREAD

**Issue by Himself65** [bumble-org/rollup-plugin-chrome-extension#24]
## How to reproduction

```bash
git clone https://github.com/Himself65/better-zhihu
cd better-zhihu
yarn
rollup -c
```

and you will find that there is no `icon.png` on dir `dist`, but

```JSON
{
  "icons": {
    "128": "static/icon.png"
  }
}
```

**Comment by jacksteamdev** [comment]
Hello, thanks for reaching out! 👍

I ran your code, and the icon.png is found in the `dist` in the `static` folder. Here's a video: [https://youtu.be/iLFXENPTRpg](url)

Can send me a screen capture of what is happening when you run the code?

Glad to help,
Jack

**Comment by Himself65** [comment]
https://youtu.be/UP4R_Q4kVu8

**Comment by AbdurRahamanAR** [comment]
I am also facing the same problem

**Comment by jacksteamdev** [comment]
We've been unable to reproduce this problem on our Linux Mint work computers. 😕 

This is a mystery to me since the rest of the operation appears to succeed in the video from @Himself65 (thanks for the video, btw).

@AbdurRahamanAR: Does rollup report any errors in the terminal? What OS are you using?

The relevant code is below, if anyone wants to take a look.

https://github.com/bumble-org/rollup-plugin-chrome-extension/blob/fbad3417d44a3949908b81a036bb51f88eb09148/src/manifest-input/index.ts#L105-L112 

https://github.com/bumble-org/rollup-plugin-chrome-extension/blob/fbad3417d44a3949908b81a036bb51f88eb09148/src/manifest-input/index.ts#L210-L228

**Comment by Himself65** [comment]
I cannot find them in the output dir, but I find `.png` images at root dir like `C://User/xxx/xxx.png`.

**Comment by jacksteamdev** [comment]
Is this with the fix or the original bug?

**Comment by jacksteamdev** [comment]
@Himself65 Is this with the fix or the original bug?

**Comment by jacksteamdev** [comment]
@Himself65 That makes sense, it seems Rollup will write files with weird filepaths without complaining.
